name: Release

on:
  push:
    branches:
      - main

jobs:
  version-analysis:
    uses: ./.github/workflows/version.yml

  build-windows:
    needs: version-analysis
    if: needs.version-analysis.outputs.should_release == 'true'
    uses: ./.github/workflows/build-windows.yml
    with:
      version: ${{ needs.version-analysis.outputs.new_version }}

  build-linux:
    needs: version-analysis
    if: needs.version-analysis.outputs.should_release == 'true'
    uses: ./.github/workflows/build-linux.yml
    with:
      version: ${{ needs.version-analysis.outputs.new_version }}

  create-release:
    needs: [version-analysis, build-windows, build-linux]
    if: needs.version-analysis.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in CMakeLists.txt
        run: |
          NEW_VERSION="${{ needs.version-analysis.outputs.new_version }}"
          sed -i "s/VERSION [0-9]*\.[0-9]*\.[0-9]*/VERSION $NEW_VERSION/" CMakeLists.txt
          echo "Updated CMakeLists.txt to version $NEW_VERSION"

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build-${{ needs.version-analysis.outputs.new_version }}
          path: ./artifacts/windows/

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-${{ needs.version-analysis.outputs.new_version }}
          path: ./artifacts/linux/

      - name: Create combined checksum file
        run: |
          echo "# Checksums for Release v${{ needs.version-analysis.outputs.new_version }}" > checksums.txt
          echo "" >> checksums.txt

          if [ -f "./artifacts/windows/"*.sha256 ]; then
            echo "## Windows x86_64" >> checksums.txt
            cat ./artifacts/windows/*.sha256 >> checksums.txt
            echo "" >> checksums.txt
          fi

          if [ -f "./artifacts/linux/"*.sha256 ]; then
            echo "## Linux x86_64" >> checksums.txt
            cat ./artifacts/linux/*.sha256 >> checksums.txt
          fi

      - name: Commit version bump and create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CMakeLists.txt
          git commit -m "chore: bump version to ${{ needs.version-analysis.outputs.new_version }}"
          git tag "v${{ needs.version-analysis.outputs.new_version }}"
          git push origin main --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ needs.version-analysis.outputs.new_version }}"
          name: "Release v${{ needs.version-analysis.outputs.new_version }}"
          body: ${{ needs.version-analysis.outputs.release_notes }}
          files: |
            ./artifacts/windows/*
            ./artifacts/linux/*
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
